### ISSUE TITLE
RedisList has compatibility issues

### ISSUE THREAD

**Issue by wy-z** [brainix/pottery#180]
Hi @brainix ~
Thank you very much for your contribution first.
'RedisList' and 'list' behave inconsistently in some cases, for example:
```
>>> l = []
>>> l[0:0] = ['a','b', 'c']
>>> l
['a', 'b', 'c']
>>> l[:] = ['a','b', 'c'] * 20
>>> l
['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c']
```

**Comment by brainix** [comment]
Hi, @wy-z. Thank you for the feedback. I'll look into how to address these issues later this week as soon as I get a break from work, and I'll keep you updated here.

**Comment by brainix** [comment]
Hi, @wy-z. I did some digging, and I'm not sure how to go about solving these incompatibility issues. Here's what I've found:

```
>>> from pottery import RedisList
>>> l = RedisList(['a', 'b', 'c'])
>>> type(l)
<class 'pottery.list.RedisList'>
>>> type(l[0:0])
<class 'list'>
>>> type(l[:])
<class 'list'>
```

The issue is that slices of a `RedisList` return `list` instances, which I believe is the correct behavior. I believe that it would be surprising behavior if every time you sliced a `RedisList`, Pottery were to create and return another `RedisList` instance within your Redis master... And even that, I don't believe, would solve this issue.

What do you think the correct path forward here should be? Any feedback is welcome!

**Comment by wy-z** [comment]
Hi, @brainix .
I think it's appropriate to return a `list` but not another `RedisList`.
How about keeping this behavior and describing it in "README"?

**Comment by brainix** [comment]
Thanks for the suggestion! I'll document these known inconsistencies and tag you on the code review.

**Comment by wy-z** [comment]
My pleasure, thanks again for your work.
